# Server Port
server:
  port: 8001

# Data Source
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 123456
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
#    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      encoding: UTF-8
      continue-on-error: false
      data-locations: classpath*:data-h2.sql
      schema-locations: classpath*:schema-h2.sql
      platform: h2
      username: sa
      password: 123456
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
#Log
logging:
  level:
    root: INFO
    org:
      hibernate: INFO
    xyz:
      fullstacks:
        demo: DEBUG
    